### ISSUE TITLE
new panel - unknown

### ISSUE THREAD

**Issue by 409H** [misterch0c/what_is_this_c2#7]
![image](https://user-images.githubusercontent.com/2313704/58881649-85597f80-86d2-11e9-9914-bcdfbe5372a3.png)

Part of a cryptocurrency malware campaign - c2 server.

https://twitter.com/sniko_/status/1135893510878576640

**Comment by misterch0c** [comment]
that's predator it seems

**Comment by viriback** [comment]
yep. predator.
